# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(910, 512)
        MainWindow.setMinimumSize(QtCore.QSize(910, 512))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_search)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gb_options = QtWidgets.QGroupBox(self.tab_search)
        self.gb_options.setMaximumSize(QtCore.QSize(16777215, 120))
        self.gb_options.setObjectName("gb_options")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gb_options)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.GL_options = QtWidgets.QGridLayout()
        self.GL_options.setObjectName("GL_options")
        self.HL_search = QtWidgets.QHBoxLayout()
        self.HL_search.setObjectName("HL_search")
        self.lbl_query = QtWidgets.QLabel(self.gb_options)
        self.lbl_query.setObjectName("lbl_query")
        self.HL_search.addWidget(self.lbl_query)
        self.tf_search = QtWidgets.QLineEdit(self.gb_options)
        self.tf_search.setObjectName("tf_search")
        self.HL_search.addWidget(self.tf_search)
        self.btn_search = QtWidgets.QPushButton(self.gb_options)
        self.btn_search.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_search.setObjectName("btn_search")
        self.HL_search.addWidget(self.btn_search)
        self.GL_options.addLayout(self.HL_search, 1, 0, 1, 1)
        self.HL_opt = QtWidgets.QHBoxLayout()
        self.HL_opt.setObjectName("HL_opt")
        self.lbl_top = QtWidgets.QLabel(self.gb_options)
        self.lbl_top.setObjectName("lbl_top")
        self.HL_opt.addWidget(self.lbl_top)
        self.cb_top = QtWidgets.QComboBox(self.gb_options)
        self.cb_top.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_top.setObjectName("cb_top")
        self.HL_opt.addWidget(self.cb_top)
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.HL_opt.addItem(spacerItem)
        self.lbl_filter = QtWidgets.QLabel(self.gb_options)
        self.lbl_filter.setObjectName("lbl_filter")
        self.HL_opt.addWidget(self.lbl_filter)
        self.cb_filter = QtWidgets.QComboBox(self.gb_options)
        self.cb_filter.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_filter.setObjectName("cb_filter")
        self.HL_opt.addWidget(self.cb_filter)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.HL_opt.addItem(spacerItem1)
        self.btn_make_analysis = QtWidgets.QPushButton(self.gb_options)
        self.btn_make_analysis.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_make_analysis.setObjectName("btn_make_analysis")
        self.HL_opt.addWidget(self.btn_make_analysis)
        self.GL_options.addLayout(self.HL_opt, 2, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.GL_options)
        self.verticalLayout_3.addWidget(self.gb_options)
        self.HL_bottom = QtWidgets.QHBoxLayout()
        self.HL_bottom.setObjectName("HL_bottom")
        self.gb_ranking = QtWidgets.QGroupBox(self.tab_search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_ranking.sizePolicy().hasHeightForWidth())
        self.gb_ranking.setSizePolicy(sizePolicy)
        self.gb_ranking.setObjectName("gb_ranking")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_ranking)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scroll_rank = QtWidgets.QScrollArea(self.gb_ranking)
        self.scroll_rank.setWidgetResizable(True)
        self.scroll_rank.setObjectName("scroll_rank")
        self.scroll_rank_items = QtWidgets.QWidget()
        self.scroll_rank_items.setGeometry(QtCore.QRect(0, 0, 405, 290))
        self.scroll_rank_items.setObjectName("scroll_rank_items")
        self.scroll_rank.setWidget(self.scroll_rank_items)
        self.verticalLayout.addWidget(self.scroll_rank)
        self.HL_bottom.addWidget(self.gb_ranking)
        self.gb_article = QtWidgets.QGroupBox(self.tab_search)
        self.gb_article.setObjectName("gb_article")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_article)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scroll_article = QtWidgets.QScrollArea(self.gb_article)
        self.scroll_article.setWidgetResizable(True)
        self.scroll_article.setObjectName("scroll_article")
        self.scroll_article_items = QtWidgets.QWidget()
        self.scroll_article_items.setGeometry(QtCore.QRect(0, 0, 405, 290))
        self.scroll_article_items.setObjectName("scroll_article_items")
        self.scroll_article.setWidget(self.scroll_article_items)
        self.verticalLayout_5.addWidget(self.scroll_article)
        self.HL_bottom.addWidget(self.gb_article)
        self.verticalLayout_3.addLayout(self.HL_bottom)
        self.tabWidget.addTab(self.tab_search, "")
        self.tab_compare = QtWidgets.QWidget()
        self.tab_compare.setObjectName("tab_compare")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_compare)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gb_references = QtWidgets.QGroupBox(self.tab_compare)
        self.gb_references.setObjectName("gb_references")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gb_references)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.HL_search_2 = QtWidgets.QHBoxLayout()
        self.HL_search_2.setObjectName("HL_search_2")
        self.lbl_ref_source = QtWidgets.QLabel(self.gb_references)
        self.lbl_ref_source.setObjectName("lbl_ref_source")
        self.HL_search_2.addWidget(self.lbl_ref_source)
        self.cb_ref_source = QtWidgets.QComboBox(self.gb_references)
        self.cb_ref_source.setObjectName("cb_ref_source")
        self.HL_search_2.addWidget(self.cb_ref_source)
        self.verticalLayout_4.addLayout(self.HL_search_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_ref_cat = QtWidgets.QLabel(self.gb_references)
        self.lbl_ref_cat.setObjectName("lbl_ref_cat")
        self.horizontalLayout_6.addWidget(self.lbl_ref_cat)
        self.cb_ref_cat = QtWidgets.QComboBox(self.gb_references)
        self.cb_ref_cat.setObjectName("cb_ref_cat")
        self.horizontalLayout_6.addWidget(self.cb_ref_cat)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_ref_top = QtWidgets.QLabel(self.gb_references)
        self.lbl_ref_top.setObjectName("lbl_ref_top")
        self.horizontalLayout_7.addWidget(self.lbl_ref_top)
        self.cb_ref_top = QtWidgets.QComboBox(self.gb_references)
        self.cb_ref_top.setObjectName("cb_ref_top")
        self.horizontalLayout_7.addWidget(self.cb_ref_top)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.btn_ref_search = QtWidgets.QPushButton(self.gb_references)
        self.btn_ref_search.setObjectName("btn_ref_search")
        self.verticalLayout_4.addWidget(self.btn_ref_search)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.VL_ref_articles = QtWidgets.QVBoxLayout()
        self.VL_ref_articles.setObjectName("VL_ref_articles")
        self.lbl_prev_articles = QtWidgets.QLabel(self.gb_references)
        self.lbl_prev_articles.setObjectName("lbl_prev_articles")
        self.VL_ref_articles.addWidget(self.lbl_prev_articles)
        self.scroll_ref_articles = QtWidgets.QScrollArea(self.gb_references)
        self.scroll_ref_articles.setWidgetResizable(True)
        self.scroll_ref_articles.setObjectName("scroll_ref_articles")
        self.scroll_ref_articles_items = QtWidgets.QWidget()
        self.scroll_ref_articles_items.setGeometry(QtCore.QRect(0, 0, 251, 160))
        self.scroll_ref_articles_items.setObjectName("scroll_ref_articles_items")
        self.scroll_ref_articles.setWidget(self.scroll_ref_articles_items)
        self.VL_ref_articles.addWidget(self.scroll_ref_articles)
        self.horizontalLayout_5.addLayout(self.VL_ref_articles)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.lbl_ref_preview = QtWidgets.QLabel(self.gb_references)
        self.lbl_ref_preview.setObjectName("lbl_ref_preview")
        self.verticalLayout_6.addWidget(self.lbl_ref_preview)
        self.scroll_ref_preview = QtWidgets.QScrollArea(self.gb_references)
        self.scroll_ref_preview.setWidgetResizable(True)
        self.scroll_ref_preview.setObjectName("scroll_ref_preview")
        self.scroll_ref_preview_items = QtWidgets.QWidget()
        self.scroll_ref_preview_items.setGeometry(QtCore.QRect(0, 0, 406, 185))
        self.scroll_ref_preview_items.setObjectName("scroll_ref_preview_items")
        self.scroll_ref_preview.setWidget(self.scroll_ref_preview_items)
        self.verticalLayout_6.addWidget(self.scroll_ref_preview)
        self.horizontalLayout.addWidget(self.gb_references)
        self.gb_results = QtWidgets.QGroupBox(self.tab_compare)
        self.gb_results.setObjectName("gb_results")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gb_results)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.HL_results = QtWidgets.QHBoxLayout()
        self.HL_results.setObjectName("HL_results")
        self.lbl_res_source = QtWidgets.QLabel(self.gb_results)
        self.lbl_res_source.setObjectName("lbl_res_source")
        self.HL_results.addWidget(self.lbl_res_source)
        self.cb_res_source = QtWidgets.QComboBox(self.gb_results)
        self.cb_res_source.setObjectName("cb_res_source")
        self.HL_results.addWidget(self.cb_res_source)
        self.VL_res_rank = QtWidgets.QVBoxLayout()
        self.VL_res_rank.setObjectName("VL_res_rank")
        self.lbl_res_rank = QtWidgets.QLabel(self.gb_results)
        self.lbl_res_rank.setObjectName("lbl_res_rank")
        self.VL_res_rank.addWidget(self.lbl_res_rank)
        self.scroll_res_rank = QtWidgets.QScrollArea(self.gb_results)
        self.scroll_res_rank.setWidgetResizable(True)
        self.scroll_res_rank.setObjectName("scroll_res_rank")
        self.scroll_res_rank_items = QtWidgets.QWidget()
        self.scroll_res_rank_items.setGeometry(QtCore.QRect(0, 0, 270, 160))
        self.scroll_res_rank_items.setObjectName("scroll_res_rank_items")
        self.scroll_res_rank.setWidget(self.scroll_res_rank_items)
        self.VL_res_rank.addWidget(self.scroll_res_rank)
        self.HL_results.addLayout(self.VL_res_rank)
        self.verticalLayout_7.addLayout(self.HL_results)
        self.lbl_result_article = QtWidgets.QLabel(self.gb_results)
        self.lbl_result_article.setObjectName("lbl_result_article")
        self.verticalLayout_7.addWidget(self.lbl_result_article)
        self.HL_articles = QtWidgets.QHBoxLayout()
        self.HL_articles.setObjectName("HL_articles")
        self.VL_articles = QtWidgets.QVBoxLayout()
        self.VL_articles.setObjectName("VL_articles")
        self.scroll_res_article = QtWidgets.QScrollArea(self.gb_results)
        self.scroll_res_article.setWidgetResizable(True)
        self.scroll_res_article.setObjectName("scroll_res_article")
        self.scroll_res_article_items = QtWidgets.QWidget()
        self.scroll_res_article_items.setGeometry(QtCore.QRect(0, 0, 402, 181))
        self.scroll_res_article_items.setObjectName("scroll_res_article_items")
        self.scroll_res_article.setWidget(self.scroll_res_article_items)
        self.VL_articles.addWidget(self.scroll_res_article)
        self.HL_articles.addLayout(self.VL_articles)
        self.verticalLayout_7.addLayout(self.HL_articles)
        self.horizontalLayout.addWidget(self.gb_results)
        self.tabWidget.addTab(self.tab_compare, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lexical Analysis"))
        self.gb_options.setTitle(_translate("MainWindow", "Options"))
        self.lbl_query.setText(_translate("MainWindow", "Query"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.lbl_top.setText(_translate("MainWindow", "Top N"))
        self.lbl_filter.setText(_translate("MainWindow", "Filter"))
        self.btn_make_analysis.setText(_translate("MainWindow", "Make Analysis"))
        self.gb_ranking.setTitle(_translate("MainWindow", "Ranking"))
        self.gb_article.setTitle(_translate("MainWindow", "Article"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), _translate("MainWindow", "Search"))
        self.gb_references.setTitle(_translate("MainWindow", "Reference"))
        self.lbl_ref_source.setText(_translate("MainWindow", "Source"))
        self.lbl_ref_cat.setText(_translate("MainWindow", "Category"))
        self.lbl_ref_top.setText(_translate("MainWindow", "Top N"))
        self.btn_ref_search.setText(_translate("MainWindow", "Search"))
        self.lbl_prev_articles.setText(_translate("MainWindow", "Articles"))
        self.lbl_ref_preview.setText(_translate("MainWindow", "Preview"))
        self.gb_results.setTitle(_translate("MainWindow", "Results"))
        self.lbl_res_source.setText(_translate("MainWindow", "Source"))
        self.lbl_res_rank.setText(_translate("MainWindow", "Ranking"))
        self.lbl_result_article.setText(_translate("MainWindow", "Article"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_compare), _translate("MainWindow", "Compare"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
